import { ContentItem } from "./types";

/**
 * Contenu de démonstration affiché tant que les Google Sheets ne sont pas
 * configurés (ou en cas d'erreur de lecture). Même forme que les lignes
 * attendues dans l'onglet "Contenus" — à remplacer par le vrai contenu du
 * cabinet directement dans Google Sheets, sans toucher au code.
 */
export const PLACEHOLDER_CONTENT: ContentItem[] = [
  {
    id: "actu-1",
    type: "actualite",
    titre: "Nouvelle session d'accompagnement pour les TPE d'Angré",
    chapo:
      "AK World Business Services lance une nouvelle vague d'accompagnement pour les petites entreprises du quartier.",
    corps:
      "Le cabinet poursuit son travail de proximité auprès des TPE et PME de la zone d'Angré : diagnostic de gestion, mise en place d'outils de suivi comptable et accompagnement personnalisé sur plusieurs mois.",
    imageUrl: "",
    datePublication: "2026-08-20",
    dateFin: "",
    departement: "Conseil & accompagnement",
    ctaLabel: "En savoir plus",
    ctaAction: "info",
    fichierUrl: "",
    visible: true,
    ordre: 1,
    infosPratiques: "",
    imageOrientation: "paysage",
  },
  {
    id: "actu-2",
    type: "promotion",
    titre: "Places limitées sur la formation Gestion de projet",
    chapo:
      "10 places offertes aux jeunes entrepreneurs pour la prochaine session de formation en gestion de projet.",
    corps:
      "Une occasion pour les porteurs de projet d'acquérir les bases essentielles de la gestion de projet, animée par les consultants du cabinet.",
    imageUrl: "",
    datePublication: "2026-08-25",
    dateFin: "2026-09-15",
    departement: "Formation professionnelle",
    ctaLabel: "Je m'inscris",
    ctaAction: "inscription",
    fichierUrl: "",
    visible: true,
    ordre: 2,
    infosPratiques: "Places limitées — priorité aux 18-35 ans porteurs de projet.",
    imageOrientation: "paysage",
  },
  {
    id: "actu-3",
    type: "actualite",
    titre: "Publication : les bonnes pratiques comptables pour les coopératives",
    chapo:
      "Un nouveau guide pratique publié par le cabinet à destination des coopératives et associations accompagnées.",
    corps:
      "Ce guide reprend les principales bonnes pratiques observées sur le terrain par les consultants d'AK World Business Services au cours des accompagnements récents.",
    imageUrl: "",
    datePublication: "2026-08-10",
    dateFin: "",
    departement: "Publication",
    ctaLabel: "En savoir plus",
    ctaAction: "info",
    fichierUrl: "",
    visible: true,
    ordre: 3,
    infosPratiques: "",
    imageOrientation: "paysage",
  },
  {
    id: "formation-gestion-projet",
    type: "formation",
    titre: "Gestion de projet",
    chapo: "Structurer, planifier et piloter un projet du démarrage à la clôture.",
    corps:
      "Formation pratique destinée aux porteurs de projet et responsables d'équipe : cadrage, planification, suivi budgétaire et gestion des risques.",
    imageUrl: "",
    datePublication: "2026-08-01",
    dateFin: "",
    departement: "Formation professionnelle",
    ctaLabel: "M'inscrire",
    ctaAction: "inscription",
    fichierUrl: "",
    visible: true,
    ordre: 4,
    infosPratiques: "Durée : 3 jours · Abidjan, Angré",
    imageOrientation: "paysage",
  },
  {
    id: "formation-rh-tpe",
    type: "formation",
    titre: "RH pour TPE",
    chapo: "Les bases de la gestion du personnel pour les petites structures.",
    corps:
      "Recrutement, contrats, obligations légales et gestion quotidienne des équipes : une formation pensée pour les dirigeants de TPE qui gèrent seuls leurs ressources humaines.",
    imageUrl: "",
    datePublication: "2026-08-01",
    dateFin: "",
    departement: "Formation professionnelle",
    ctaLabel: "M'inscrire",
    ctaAction: "inscription",
    fichierUrl: "",
    visible: true,
    ordre: 5,
    infosPratiques: "Durée : 2 jours · Abidjan, Angré",
    imageOrientation: "paysage",
  },
  {
    id: "formation-marketing-digital",
    type: "formation",
    titre: "Marketing digital",
    chapo: "Développer sa visibilité et ses ventes en ligne.",
    corps:
      "Réseaux sociaux, contenu, publicité en ligne : une initiation concrète pour les entrepreneurs qui veulent développer leur présence digitale sans budget agence.",
    imageUrl: "",
    datePublication: "2026-08-01",
    dateFin: "",
    departement: "Formation professionnelle",
    ctaLabel: "M'inscrire",
    ctaAction: "inscription",
    fichierUrl: "",
    visible: true,
    ordre: 6,
    infosPratiques: "Durée : 2 jours · Abidjan, Angré",
    imageOrientation: "paysage",
  },
  {
    id: "ebook-piloter-sa-tpe",
    type: "ebook",
    titre: "Piloter sa TPE",
    chapo: "Le guide pratique pour garder le contrôle de sa gestion au quotidien.",
    corps:
      "Un ebook synthétique pour comprendre les indicateurs essentiels à suivre lorsqu'on dirige une petite entreprise en Côte d'Ivoire.",
    imageUrl: "",
    datePublication: "2026-07-15",
    dateFin: "",
    departement: "Ressources",
    ctaLabel: "Télécharger",
    ctaAction: "telechargement",
    fichierUrl: "",
    visible: true,
    ordre: 7,
    infosPratiques: "Format PDF · 24 pages",
    imageOrientation: "paysage",
  },
  {
    id: "ebook-jeunes-entrepreneuriat",
    type: "ebook",
    titre: "Jeunes et entrepreneuriat",
    chapo: "De l'idée au premier client : un parcours simplifié pour se lancer.",
    corps:
      "Destiné aux jeunes porteurs de projet, ce guide reprend les étapes clés pour structurer une idée et passer à l'action.",
    imageUrl: "",
    datePublication: "2026-07-01",
    dateFin: "",
    departement: "Ressources",
    ctaLabel: "Télécharger",
    ctaAction: "telechargement",
    fichierUrl: "",
    visible: true,
    ordre: 8,
    infosPratiques: "Format PDF · 18 pages",
    imageOrientation: "paysage",
  },
];
